### ISSUE TITLE
兄弟你这个太占cpu

### ISSUE THREAD

**Issue by hanke-cnc** [Wz-Ming/tcpTransferFile#1]

**Comment by hanke-cnc** [comment]
功能倒是没啥问题,就是占用cpu,在嵌入式cpu上有点顶不住

**Comment by zhangming-wang** [comment]
这我还真没想到，但我这边嵌入式CPU是够用的，可能是我开了两个线程的缘故

**Comment by hanke-cnc** [comment]
> 这我还真没想到，但我这边嵌入式CPU是够用的，可能是我开了两个线程的缘故

我也是在mp157上跑呀,150%的cpu占用,注释掉后50%,有时候会使得主ui界面点按钮卡顿,你这个我是一股脑导进我的程序里的,反正能用,但是不好改,我通过注释运行查到是 void receiveThread::run() 里面卡,

![aaa](https://user-images.githubusercontent.com/108179425/192948614-abda79f4-0ff0-4dbe-a7a1-275b040c65af.png)

**Comment by Wz-Ming** [comment]
难怪你卡，我跑的CPU和你跑的性能差很多
![image](https://user-images.githubusercontent.com/71966407/192950599-e8f4bd90-b37f-4fe9-8ff0-ee00468b9c62.png)

**Comment by Wz-Ming** [comment]
> > 这我还真没想到，但我这边嵌入式CPU是够用的，可能是我开了两个线程的缘故
> 
> 我也是在mp157上跑呀,150%的cpu占用,注释掉后50%,有时候会使得主ui界面点按钮卡顿,你这个我是一股脑导进我的程序里的,反正能用,但是不好改,我通过注释运行查到是 void receiveThread::run() 里面卡,
> 
> ![aaa](https://user-images.githubusercontent.com/108179425/192948614-abda79f4-0ff0-4dbe-a7a1-275b040c65af.png)

难怪你卡，我跑的CPU和你跑的CPU性能差很多
![image](https://user-images.githubusercontent.com/71966407/192950889-8e9edb13-07f5-4f7c-a436-80c327cbe90d.png)
